# Generated by Django 4.0.3 on 2022-03-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ln',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
