# Generated by Django 4.0.3 on 2022-03-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_userprofile_ln'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
