# Generated by Django 4.0.3 on 2022-03-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_userprofile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
