# Generated by Django 4.0.3 on 2022-03-25 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_userprofile_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.TextField(blank=True, max_length=10, null=True)),
                ('social_status', models.TextField(blank=True, max_length=10, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('educational_qualification', models.TextField(blank=True, max_length=40, null=True)),
                ('total_qualification', models.FloatField(blank=True, default=0, null=True)),
                ('recording_type', models.TextField(blank=True, max_length=10, null=True)),
                ('transfer_destination', models.TextField(blank=True, max_length=200, null=True)),
                ('student_type', models.TextField(blank=True, max_length=10, null=True)),
                ('army_status', models.TextField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_created_by', to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_nationality', to='main_site.nationalities')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_system', to='main_site.systems')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_team', to='main_site.teams')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Student_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
