# Generated by Django 4.0.3 on 2022-03-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='code',
            new_name='new_pass',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='new_pass_as',
            field=models.BooleanField(default=True),
        ),
    ]
